spring:
  application:
    name: api-gateway

  ## Gateway configurations
  cloud:
    gateway:
      routes:
        ## authentication-service
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication-service/**
          filters:
            - StripPrefix=1

        ## additional services go here
        
server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka